### ISSUE TITLE
[Enhancement] - Pinned Message Icons

### ISSUE THREAD

**Issue by BigFlubba** [Neodymium7/BetterDiscordStuff#2]
Can the icon be more to the left if not all the way to the left of the message, or at least the option to move it? Some of the ideas I have are here...
![image](https://user-images.githubusercontent.com/69104450/157775900-9d8566cb-80aa-494b-9ab2-0fda9c12c7e4.png)
Options 1 and 2 are my preferred choices but I would like for it to be either one of those.

**Comment by Neodymium7** [comment]
You can already change the positioning with CSS! Here's something I quickly wrote that puts the icon to the top left. Placement on the left is a bit tricky due to how much is going on there like avatars, timestamps, etc. (which is why I decided to put it on the right in the plugin), so I had to move some other stuff over for it to fit. Feel free to tweak it until you find something you like!
```css
.pinned-message-icon {
    left: 10px;
    top: 3px;
}
.message-2CShn3.groupStart-3Mlgv1 .pinned-message-icon {
    top: 14px;
}
.message-2CShn3.groupStart-3Mlgv1.pinned-message .contents-2MsGLg,
.message-2CShn3.groupStart-3Mlgv1.pinned-message .contents-2MsGLg .avatar-2e8lTP {
    margin-left: 24px;
}
.mouse-mode.full-motion .message-2CShn3:not(.groupStart-3Mlgv1):hover .pinned-message-icon {
    display: none;
}
```
